/**
 * Known audit log action identifiers. Kept as string constants (not a
 * Prisma enum) so new admin actions can be added by any future module
 * without a schema migration — see AuditLog.action in schema.prisma.
 */
export const AUDIT_ACTIONS = {
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN_LOGOUT: 'ADMIN_LOGOUT',
  ADMIN_REFRESH_TOKEN: 'ADMIN_REFRESH_TOKEN',
  ADMIN_CREATE: 'ADMIN_CREATE',
  ADMIN_CHANGE_PASSWORD: 'ADMIN_CHANGE_PASSWORD',

  CREATE_CATEGORY: 'CREATE_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  CREATE_AI_TOOL: 'CREATE_AI_TOOL',
  UPDATE_AI_TOOL: 'UPDATE_AI_TOOL',
  DELETE_AI_TOOL: 'DELETE_AI_TOOL',

  CREATE_TAG: 'CREATE_TAG',
  UPDATE_TAG: 'UPDATE_TAG',
  DELETE_TAG: 'DELETE_TAG',

  CREATE_PROMPT: 'CREATE_PROMPT',
  UPDATE_PROMPT: 'UPDATE_PROMPT',
  DELETE_PROMPT: 'DELETE_PROMPT',
  DUPLICATE_PROMPT: 'DUPLICATE_PROMPT',
  PUBLISH_PROMPT: 'PUBLISH_PROMPT',
  UNPUBLISH_PROMPT: 'UNPUBLISH_PROMPT',
  ARCHIVE_PROMPT: 'ARCHIVE_PROMPT',

  UPLOAD_MEDIA: 'UPLOAD_MEDIA',
  REPLACE_MEDIA: 'REPLACE_MEDIA',
  DELETE_MEDIA: 'DELETE_MEDIA',
  REORDER_MEDIA: 'REORDER_MEDIA',

  CREATE_HOME_SECTION: 'CREATE_HOME_SECTION',
  UPDATE_HOME_SECTION: 'UPDATE_HOME_SECTION',
  DELETE_HOME_SECTION: 'DELETE_HOME_SECTION',

  RECALCULATE_TRENDING: 'RECALCULATE_TRENDING',

  UPDATE_REPORT_STATUS: 'UPDATE_REPORT_STATUS',
  UPDATE_ADMIN_USER: 'UPDATE_ADMIN_USER',
  DELETE_ADMIN_USER: 'DELETE_ADMIN_USER',

  // Reserved for later phases (Sections 24, 27, 26):
  UPDATE_AD_CONFIG: 'UPDATE_AD_CONFIG',
  UPDATE_APP_CONFIG: 'UPDATE_APP_CONFIG',
  UPDATE_VERSION: 'UPDATE_VERSION',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
